# Generated by Django 5.2.5 on 2025-09-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductList",
            fields=[
                ("pid", models.IntegerField(primary_key=True, serialize=False)),
                ("pname", models.TextField(max_length=50)),
                ("category", models.TextField(max_length=20)),
                ("price", models.FloatField()),
                ("description", models.TextField(max_length=100)),
            ],
        ),
    ]
